apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  api-url: {{ .Values.config.apiUrl | quote }}
  cors-origins: {{ .Values.config.corsOrigins | quote }}
  environment: {{ .Values.config.environment | quote }}
  log-level: {{ .Values.config.logLevel | quote }}
